### ISSUE TITLE
ImportError: cannot import name 'izip_longest'

### ISSUE THREAD

**Issue by mpenkov** [redacted/XKCD-password-generator#82]
I get this on Python 3.6:

```
sergeyich:dbi2 misha$ xkcdpassword
Traceback (most recent call last):
  File "/Users/misha/envs/dbi2/bin/xkcdpassword", line 7, in <module>
    from xkcdpassword.xkcdpassword import main
  File "/Users/misha/envs/dbi2/lib/python3.6/site-packages/xkcdpassword/xkcdpassword.py", line 5, in <module>
    from itertools import izip_longest
ImportError: cannot import name 'izip_longest'
```

**Comment by redacted** [comment]
Hey, I think you have opened this issue against the wrong implementation - I don't use itertools anywhere. Looked around and I think this is the repo you want https://github.com/dougwritescode/xkcdpassword/blob/master/xkcdpassword/xkcdpassword.py

**Comment by mpenkov** [comment]
Whoops, sorry!
